server:
  port: 7777
spring:
  base_url: /api/v1/
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/hygiai_auth
    username: root
    password: password
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update #create # update #
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  sql:
    init:
      mode: always
  main:
    allow-bean-definition-overriding: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  hystrix:
    enabled: true



keycloak:
  serverUrl: http://localhost:8180/auth
  realm: hygiai_realm
  clientId: admin-cli #hygiai_app-client
  clientSecret: WXiLedK0sLydM6QZs8XES98Skrntd0sF
  userName: user_admin
  password: admin
  resteasy_pool_size: 10


HHTPSource:
  cert-path: "dfsf"
  cert-pass: "ddfsdf"